# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c3c608ffbf3fca2fa088fbe46b84e913d16ab8e2ef116f218e474093683e1d4e16d971b57a8b7f5ab1d23f77992fb15db6a8664830e70bd60c0c78c08d2a8d5

test:
  secret_key_base: 66a5d6d164f8240afbcb37b3b522d63896a6a853df9296dd57fe8ba36d7eb7a8a95458dac7bb32e533c577f98122c228867a8fe76995c6248fb49d7025df612b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
